stages:
  data_ingestion:
    cmd: python ml_pipeline/src/pipeline/stage_01_data_ingestion.py
    deps:
      - ml_pipeline/src/pipeline/stage_01_data_ingestion.py
      - ml_pipeline/src/components/data_ingestion.py
    outs:
      - ml_pipeline/src/artifacts/training_data

  training:
    cmd: python ml_pipeline/src/pipeline/stage_02_model_train.py
    deps:
      - ml_pipeline/src/pipeline/stage_02_model_train.py
      - ml_pipeline/src/configs/data.yaml
      - ml_pipeline/src/configs/params.yaml
      - ml_pipeline/src/artifacts/training_data
    params:
      - ml_pipeline/src/configs/params.yaml:
          - train.epochs
          - train.batch
          - train.imgsz
    outs:
      - ml_pipeline/src/artifacts/model
