# Data Pipeline Configuration
# This file defines settings for the data processing pipeline
# Used by Apache Airflow DAGs and data processing scripts

# General settings
general:
  project_name: "moppy_perception"
  environment: "development"  # Options: development, staging, production
  
# Data sources
data_sources:
  simulation:
    type: "local"
    base_path: "./data"
    latest_symlink: "./data/latest"
    format: "mixed"  # Contains both CSV and image files
    schema_version: "1.0.0"
  
# Data processing
processing:
  # Image preprocessing settings
  image:
    resize_dims: [224, 224]  # Target dimensions for model input
    normalization: "imagenet"  # Options: imagenet, [-1,1], [0,1]
    augmentation:
      enabled: true
      horizontal_flip: true
      rotation_range: 10
      brightness_range: [0.8, 1.2]
      
  # LiDAR preprocessing settings
  lidar:
    max_range: 5.0  # Maximum range to consider (meters)
    min_range: 0.1  # Minimum range to consider (meters)
    feature_engineering:
      enabled: true
      compute_statistics: true  # Compute mean, median, min, max, etc.
      range_buckets: 10  # Number of buckets for histograms
      
  # Data split settings
  split:
    train_ratio: 0.7
    val_ratio: 0.15
    test_ratio: 0.15
    random_seed: 42
    stratify: true  # Maintain class distribution in splits
    
  # Obstacle and surface detection thresholds
  thresholds:
    obstacle_detection:
      lidar_distance: 0.5  # Meters
      confidence: 0.75
    floor_classification:
      min_area_pct: 0.2  # Minimum floor area percentage in image
      
# MLflow tracking
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "moppy_perception"
  registry_uri: "sqlite:///mlflow.db"
  artifact_location: "./mlruns"
  
# Model settings
model:
  obstacle_detector:
    type: "cnn"
    architecture: "mobilenet_v2"
    input_shape: [224, 224, 3]
    pretrained: true
    fine_tune_layers: 5
    
  surface_classifier:
    type: "cnn"
    architecture: "efficientnet_b0"
    input_shape: [224, 224, 3]
    num_classes: 4  # tile, carpet, wood, other
    pretrained: true
    
# Training settings
training:
  batch_size: 32
  epochs: 50
  early_stopping:
    enabled: true
    patience: 10
    monitor: "val_loss"
  optimizer:
    name: "adam"
    learning_rate: 0.001
    weight_decay: 0.0001
  scheduler:
    enabled: true
    type: "reduce_on_plateau"
    patience: 5
    factor: 0.5
    
# Evaluation settings
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "confusion_matrix"
  thresholds:
    min_accuracy: 0.85
    min_f1_score: 0.80
    
# Deployment settings
deployment:
  target: "raspberry_pi"
  optimization:
    quantization: true
    pruning: false
    input_type: "uint8"  # For quantized models
  export_formats:
    - "tflite"
    - "onnx"
  metadata:
    include_preprocessing: true
    include_class_names: true
    compatibility_version: "1.0"

# Airflow DAG settings
airflow:
  dag_name: "moppy_perception_pipeline"
  schedule_interval: "0 0 * * *"  # Daily at midnight
  start_date: "2023-01-01"
  retries: 3
  retry_delay_minutes: 5
  email_on_failure: true
  timeout_minutes: 120
  max_active_runs: 1
  concurrency: 4 